name: Documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate_documentation:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup git
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 -R ~/.ssh
          eval "$(ssh-agent -s)"
          ssh-add
          ssh git@github.com || true
          git config --global user.name 'graalvm bot'
          git config --global user.email 'graalvmbot@users.noreply.github.com'
      - name: Build and publish documentation
        run: |
          echo "org.ajoberstar.grgit.auth.command.allow=true" >> gradle.properties
          ./gradlew :docs:gitPublishPush
