name: JVM Reachability Metadata Repository

on:
  push:
    paths:
      - 'common/jvm-reachability-metadata/**'
  pull_request:
    paths:
      - 'common/jvm-reachability-metadata/**'
  workflow_dispatch:

jobs:
  test-jvm-reachability-metadata:
    name:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkstyle
        run: ./gradlew :jvm-reachability-metadata:checkstyleMain :jvm-reachability-metadata:checkstyleTest
      - name: JVM test
        run: ./gradlew :jvm-reachability-metadata:test
      - name: Tests results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: tests-results
          path: common/jvm-reachability-metadata/build/reports/tests/
