name: native-maven-plugin

on:
  push:
    paths:
      - 'native-maven-plugin/**'
      - 'samples/**'
      - 'common/**'
  pull_request:
    paths:
      - 'native-maven-plugin/**'
      - 'samples/**'
      - 'common/**'
  workflow_dispatch:

jobs:
  test-native-maven-plugin:
    name:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check and test the plugin
        run: ./gradlew :native-maven-plugin:check --no-daemon
      - name: Tests results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: functional-tests-results-${{ matrix.gradle-version }}
          path: native-maven-plugin/build/reports/tests/
